import LearningFrameworkPage from "../../components/LearningFrameworkPage";

const FRAMEWORK = {
  id: "iso27701",
  name: "ISO/IEC 27701:2019 Privacy Information Management",
  region: "Global",
  flag: "🌐",
  flagAnimation: "float",
  basePath: "/iso-27701",
  color: "purple",
  weeks: 4,
  milestones: 3,
  referenceUrl: "https://www.iso.org/standard/71670.html",
  weeksData: [
    {
      week: 1,
      title: "Foundation — PIMS Structure & Privacy Principles",
      description:
        "Understand ISO 27701 as the Privacy Information Management System (PIMS) extension to ISO 27001/27002. Establish the distinction between PII controllers and PII processors, map core privacy principles, and define the scope of your PIMS within the broader information security management system (ISMS).",
      tasks: [
        {
          title: "Map ISO 27701 structure as PIMS extension to ISO 27001",
          control: "ISO 27701 Clauses 5–8 (PIMS requirements mapped to ISO 27001 clauses)",
          how: "Review how ISO 27701 layers privacy-specific requirements on top of the ISO 27001 ISMS framework. Document that the PIMS adopts the same Plan-Do-Check-Act (PDCA) cycle, same risk-based thinking, and same clause structure (context, leadership, planning, support, operation, performance evaluation, improvement). Create a cross-reference matrix mapping each ISO 27701 clause to its corresponding ISO 27001 clause. Note that ISO 27701 Clause 6.1.1 through 6.1.3 extends the risk assessment and treatment process specifically for privacy risks. Understand that the PIMS can be certified independently or integrated into an existing ISO 27001 certification scope.",
          check: "Cross-reference matrix completed mapping all ISO 27701 clauses to ISO 27001. Risk assessment methodology updated to include privacy-specific risks. Scope statement for the PIMS drafted and reviewed against the existing ISMS scope."
        },
        {
          title: "Distinguish PII controllers from PII processors under the standard",
          control: "ISO 27701 Clauses 7.2 (PII controllers) and 8.2 (PII processors)",
          how: "Classify your organization's roles: are you a PII controller (determining purposes and means of processing), a PII processor (processing on behalf of a controller), or both? For controllers, ISO 27701 Clause 7 specifies additional requirements including lawful basis for processing, PII subject rights, and privacy by design. For processors, Clause 8 adds requirements around contractual obligations to controllers, sub-processor management, and assisting controllers with DSARs. Document each role your organization holds for each processing activity. Map the GDPR Article 28 (processor obligations) and Article 46 (transfer safeguards) requirements directly into your PIMS documentation. If your organization acts as a processor, ensure your contracts with controllers reflect the ISO 27701 Clause 8.3 sub-processing requirements.",
          check: "Organization's PII controller and processor roles documented for every processing activity. GDPR Article 28 processor contract requirements mapped to ISO 27701 Clause 8.3. GDPR Article 46 transfer mechanism requirements identified. Role classification reviewed by legal and DPO."
        },
        {
          title: "Define and document privacy principles aligned with ISO 27701",
          control: "ISO 27701 Clauses 7.3–7.13 (controller-specific controls) and applicable Annex A controls",
          how: "Document how your organization addresses each core privacy principle: (1) Consent and contract-based processing, (2) Legitimate interest balancing, (3) Processing limitation and purpose specification, (4) Data minimization, (5) Accuracy and rectification, (6) Storage limitation and retention, (7) Data subject rights (access, erasure, portability, objection, restriction), (8) Confidentiality and security of processing, (9) Cross-border transfer safeguards, (10) Accountability and documentation, (11) Privacy by design and by default, (12) Protection of PII of children, (13) Automated decision-making and profiling safeguards. For each principle, create a policy statement describing how your PIMS implements it. Reference the corresponding GDPR Articles (e.g., Article 5 for principles, Articles 12–22 for data subject rights) and any analogous requirements under CCPA, LGPD, or DPDPA.",
          check: "Privacy principles policy document created with entries for all 13 principle areas. Each policy statement references both ISO 27701 clause and corresponding GDPR/CCPA articles. Policy approved by DPO and senior management. Distributed to all relevant staff."
        },
        {
          title: "Establish PIMS scope and boundary documentation",
          control: "ISO 27701 Clause 4.3 (scope of the PIMS) and ISO 27001 Clause 4.3",
          how: "Define the boundaries of your PIMS by identifying: (1) all business units and locations that process PII, (2) all categories of PII processed (employees, customers, prospects, vendors, website visitors), (3) all technology systems that store or process PII, (4) all third parties who receive or process PII, (5) all jurisdictions where PII is processed or transferred. Document external and internal issues relevant to privacy (e.g., regulatory landscape, organizational structure, contractual obligations). Create a scope document that explicitly states what is included and excluded from the PIMS. If you already have an ISO 27001 scope statement, create a companion PIMS scope that references it. Ensure top management reviews and approves the scope per Clause 4.3.",
          check: "PIMS scope document completed covering all PII processing locations, systems, and third parties. External/internal privacy context issues documented. Scope approved by top management. Scope cross-referenced with existing ISO 27001 ISMS scope for consistency."
        },
        {
          title: "Set up PIMS governance and assign privacy roles",
          control: "ISO 27701 Clause 5.3 (roles, responsibility, and authority) and Clause 6.1.2 (risk assessment)",
          how: "Establish the governance structure for your PIMS: (1) Appoint a Privacy Information Manager or equivalent role responsible for PIMS operation. (2) Define reporting lines — this role should report to top management. (3) Assign privacy responsibilities to existing roles (HR, IT, Legal, Marketing, Sales, Product). (4) Establish a Privacy Steering Committee or working group that meets regularly. (5) Define the competence requirements for privacy-related roles. (6) Create an awareness program covering privacy principles and PIMS procedures. (7) Document how privacy responsibilities interact with information security responsibilities if both ISMS and PIMS are in scope. Ensure at least one person has formal training in privacy management (e.g., CIPP/E, CIPM, or ISO 27701 Lead Auditor).",
          check: "Privacy Information Manager role defined with documented responsibilities. Privacy Steering Committee charter created. Responsibility assignment matrix (RACI) completed for all PIMS processes. Awareness training program for PIMS launched. Competence records maintained for key privacy roles."
        }
      ]
    },
    {
      week: 2,
      title: "Implementation — ROPA, DPIA, PII Inventory & Consent",
      description:
        "Implement the core operational controls of the PIMS. Build your Record of Processing Activities (ROPA) with all 14 GDPR Article 30 fields, establish Data Protection Impact Assessment (DPIA) triggers and process, create comprehensive PII inventory and mapping, design privacy notices, and build consent mechanisms. This week is critical for operationalizing privacy compliance.",
      tasks: [
        {
          title: "Implement ROPA (Record of Processing Activities) with all 14 GDPR Art. 30 fields",
          control: "ISO 27701 Clause 7.3 (consent) and Clause 7.8 (privacy impact assessment), GDPR Article 30",
          how: "ROPA is REQUIRED under GDPR Article 30 for controllers with 250+ employees (and controllers with fewer than 250 if processing is not occasional, likely to result in risk, or involves special category data). It is also REQUIRED for processors under GDPR Article 30(2). Build your ROPA covering these 14 fields: (1) Name and contact details of the controller/processor, (2) Purposes of the processing, (3) Description of categories of data subjects, (4) Description of categories of personal data, (5) Categories of recipients (internal and external), (6) Transfers to third countries including identification of country and safeguards (GDPR Article 46 mechanisms), (7) Envisaged time limits for erasure of different data categories, (8) Description of technical and organizational security measures, (9) Description of processing operations and methods, (10) Legal basis for each processing activity (consent, contract, legal obligation, vital interests, public task, legitimate interest per GDPR Article 6), (11) Where consent is the basis — how consent is obtained and managed, (12) Whether data is transferred outside the EEA and the mechanism used, (13) Details of any automated decision-making or profiling, (14) Data processor details including sub-processors. Use a tool like OneTrust, TrustArc, or a structured spreadsheet. Update ROPA at least quarterly and whenever new processing activities begin. Implement in ISO 27701 terms: treat ROPA as a living operational document per Clause 7.3 and integrate it into your risk assessment per Clause 6.1.2.",
          check: "ROPA document created with all 14 GDPR Article 30 fields populated for every processing activity. Legal basis documented for each processing activity. Update frequency defined (at minimum quarterly). ROPA reviewed by DPO. Tool or spreadsheet version-controlled. Sub-processor list maintained within ROPA. Cross-border transfers identified with Article 46 safeguards documented."
        },
        {
          title: "Establish DPIA triggers, process, and documentation",
          control: "ISO 27701 Clause 7.8 (privacy impact assessment), GDPR Article 35 (DPIA requirement)",
          how: "DPIAs are REQUIRED under GDPR Article 35 when processing is 'likely to result in a high risk to the rights and freedoms of natural persons.' DPIA triggers include: (1) Systematic and extensive profiling with significant effects, (2) Large-scale processing of special categories of data or criminal data, (3) Systematic monitoring of public areas. Additional triggers under various supervisory authority guidelines include: new technologies, vulnerable data subjects, processing that prevents exercise of rights, matching or combining datasets, data concerning vulnerable individuals, innovative use of data, and cross-border processing. Build your DPIA process: (a) Screening checklist to determine if DPIA is needed, (b) DPIA template covering: description of processing, necessity and proportionality, risks to data subjects, measures to mitigate risks, (c) Consultation step — if residual risk remains high after mitigation, consult the supervisory authority per GDPR Article 36, (d) Integration with risk management — DPIA findings feed into your PIMS risk register per ISO 27701 Clause 6.1.2. Within ISO 27701, implement this as Clause 7.8 requiring PII controllers to conduct privacy impact assessments and PII processors to assist. Document the DPIA process, assign a DPA (Data Protection Assessment) owner for each assessment, and maintain a DPIA register.",
          check: "DPIA screening checklist created and operational. DPIA template document completed with all required fields. DPIA process documented end-to-end including consultation with DPA and supervisory authority. At least one DPIA conducted for a current high-risk processing activity. DPIA register maintained tracking all assessments and their status. Residual risk assessment and mitigation measures documented."
        },
        {
          title: "Build comprehensive PII inventory and data mapping",
          control: "ISO 27701 Clause 7.3 (processing limitation), Clause 7.7 (privacy by design and by default)",
          how: "Create a complete inventory of all PII your organization processes. For each data set, document: (1) Data category (e.g., name, email, financial, health, biometric), (2) Source of the data (direct from subject, third party, public source), (3) System(s) where it is stored (databases, SaaS tools, file shares, backups), (4) Format (digital, paper), (5) Who has access (roles and departments), (6) Retention period and disposal method, (7) Where it flows (internal transfers, external recipients, international transfers), (8) Legal basis for processing, (9) Encryption status at rest and in transit, (10) Anonymization or pseudonymization applied. Create data flow diagrams showing PII movement across systems. Cross-reference with your ROPA to ensure completeness. Use this inventory to validate your PIMS scope. For ISO 27701 compliance, the inventory supports the processing limitation principle (Clause 7.3) and privacy by design requirements (Clause 7.7). Consider automated discovery tools (e.g., BigID, Varonis, Spirion) for continuous PII discovery.",
          check: "PII inventory document or tool populated with all PII categories, sources, systems, recipients, and retention. Data flow diagrams created for at least the top 5 PII processing activities. Inventory cross-referenced with ROPA for consistency. Data flows across international boundaries identified. Inventory reviewed by data owners. Update process defined (at least semi-annually)."
        },
        {
          title: "Design and implement privacy notices",
          control: "ISO 27701 Clause 7.3 (consent and contract), Clause 7.4 (privacy notice to data subjects)",
          how: "Privacy notices are REQUIRED for all PII processing. Under ISO 27701 Clause 7.4 and GDPR Articles 13 and 14, each notice must include: (1) Identity and contact details of the controller and DPO, (2) Purposes and legal basis for processing, (3) Legitimate interests pursued (if applicable), (4) Categories of recipients, (5) Details of international transfers and safeguards, (6) Retention periods or criteria for determining them, (7) Data subject rights (access, rectification, erasure, restriction, portability, objection), (8) Right to withdraw consent, (9) Right to lodge a complaint with a supervisory authority, (10) Whether provision of data is a statutory/contractual requirement, (11) Existence of automated decision-making including profiling, (12) Source of the data (if not collected directly). Create separate notices for: employees, customers, website visitors, marketing recipients, job applicants, and vendors. Implement layered notices (short summary + detailed version). Ensure notices are available in all relevant languages and accessible at every point of data collection (just-in-time notices). Review notices at least annually or when processing changes.",
          check: "Privacy notices created for all stakeholder groups (employees, customers, website, marketing, applicants). Each notice contains all 12 GDPR Article 13/14 required elements. Layered notice design implemented (summary + detailed). Notices translated to all relevant languages. Just-in-time notices placed at data collection points. Annual review process scheduled and documented."
        },
        {
          title: "Implement consent mechanisms and preference management",
          control: "ISO 27701 Clause 7.3 (consent), GDPR Article 7 (conditions for consent), ePrivacy Directive",
          how: "Build consent mechanisms that meet GDPR's strict requirements: (1) Consent must be freely given, specific, informed, and unambiguous — use clear affirmative action (pre-ticked boxes are invalid), (2) Consent must be separate from other terms — do not bundle consent with terms acceptance, (3) Consent must be as easy to withdraw as to give, (4) Maintain auditable records of when and how consent was obtained. Implement a Consent Management Platform (CMP) that: (a) Presents granular consent options (analytics, marketing, personalization, third-party sharing), (b) Records consent with timestamp, version of notice shown, and method of collection, (c) Provides a preference center where users can modify their choices, (d) Propagates withdrawal across all systems within 24 hours, (e) Handles re-consent campaigns when purposes change. For B2B contexts where legitimate interest may apply, document the balancing test and offer opt-out. For CCPA compliance, implement the 'Do Not Sell or Share My Personal Information' link. For LGPD, recognize that consent must be free and informed with specific purpose. For DPDPA, implement verifiable consent for processing of children's data. Integrate the CMP with your ROPA to track which consent mechanisms apply to each processing activity.",
          check: "CMP implemented with granular consent options across all data collection points. Consent records stored with timestamps and notice versions. Preference center live and accessible. Withdrawal mechanism tested — confirmed as easy as giving consent. Re-consent process documented. CCPA 'Do Not Sell' link implemented. Consent propagation across systems verified. Auditable consent trail maintained."
        }
      ]
    },
    {
      week: 3,
      title: "Verification — Privacy Controls Testing & DSAR Handling",
      description:
        "Verify that your PIMS privacy controls are working effectively. Test Annex A and Annex B privacy controls, validate Data Subject Access Request (DSAR) handling procedures, verify PII retention and disposal practices, and assess the privacy impact of new and existing systems.",
      tasks: [
        {
          title: "Test ISO 27701 Annex A (controllers) and Annex B (processors) controls",
          control: "ISO 27701 Annex A (PII controller controls) and Annex B (PII processor controls)",
          how: "Develop and execute test procedures for key controls in both annexes. Annex A controller controls to test: A.5.4 (Privacy risks), A.6.1 (PII identification and mapping), A.6.12 (PII disposal), A.7.1 (Condition for processing PII), A.7.2 (Consent), A.7.3 (Privacy by design), A.7.4 (Processor selection), A.7.5 (Processor agreement), A.8.1–8.9 (DSARs, complaints, disclosure, data portability). Annex B processor controls to test: B.5.4 (Privacy risks), B.6.2 (Special categories identification), B.7.1 (Processing only on documented instructions), B.7.2 (Personnel), B.7.3 (Sub-processing), B.8.1–8.5 (Assistance to controllers, DSARs, data breach notification, deletion/return of PII). For each control, create: (a) A test procedure describing how to verify effectiveness, (b) Expected evidence or artifacts, (c) Acceptance criteria, (d) Test results and findings. Use a combination of documentary review, interviews, observation, and technical testing. Perform testing at least annually and whenever significant changes occur.",
          check: "Test plan created covering all material Annex A and Annex B controls. Test procedures defined for each control with evidence requirements. Testing executed with documented results. Findings logged in a privacy issues register. Remediation plans created for all non-conformities. Follow-up testing scheduled for critical findings."
        },
        {
          title: "Verify DSAR (Data Subject Access Request) handling process end-to-end",
          control: "ISO 27701 Clause 8.5 (processor assistance with DSARs), GDPR Articles 15–22",
          how: "DSARs are a fundamental requirement under GDPR Articles 15–22 and ISO 27701 Clauses 8.5 (processor) and the controller-specific provisions. Verify the full DSAR lifecycle: (1) **Receipt and logging**: Confirm DSARs can be submitted via multiple channels (email, web form, phone) and are logged in a central system with unique reference numbers, (2) **Identity verification**: Test that identity verification is performed before processing (proportionate to risk — do not over-verify), (3) **Assessment**: Confirm the DPO or privacy team assesses each DSAR within the mandated timeframe (1 month, extendable to 3 months for complex requests under GDPR Article 12(3)), (4) **Exemptions**: Verify that exemptions are applied correctly (e.g., third-party data, legal privilege, manifestly unfounded requests), (5) **Data gathering**: Test that all relevant systems are queried and data is compiled, (6) **Review**: Confirm a privacy-trained reviewer checks the response before disclosure, (7) **Delivery**: Verify the response is provided in a commonly used electronic format (for EIRs/portability requests), (8) **Logging**: Confirm the DSAR is logged with date, type, outcome, and any exemptions used. Test each DSAR type: access (Art. 15), rectification (Art. 16), erasure (Art. 17), restriction (Art. 18), portability (Art. 20), objection (Art. 21), automated decision-making (Art. 22). Simulate a DSAR end-to-end and time each stage. Verify processor assistance per ISO 27701 Clause 8.5 — processors must support controllers with DSARs within contractually agreed timelines.",
          check: "DSAR procedure document reviewed and complete. Simulated DSAR processed end-to-end within 1 month. Identity verification proportionate and documented. Exemptions documented with legal basis. Response includes all required information per GDPR Article 15/16/17/18/20/21/22. DSAR register maintained with statistics (volume, response time, exemptions used). Processor assistance mechanism tested with at least one processor. Staff awareness confirmed through testing."
        },
        {
          title: "Verify PII retention schedules and secure disposal practices",
          control: "ISO 27701 Clause 7.6 (retention and disposal), Clause 8.4 (processor return/deletion), A.6.12 (disposal)",
          how: "Retention and disposal are critical under ISO 27701 Clause 7.6 for controllers and Clause 8.4 for processors. Verify: (1) **Retention schedules**: Confirm that every category of PII in your inventory has a defined retention period based on legal, regulatory, and business requirements. Common retention bases include: contractual obligations, statutory requirements (e.g., tax records 7 years, employment records 6 years post-termination in many jurisdictions), legitimate interest, and consent duration. (2) **Automated enforcement**: Test that retention schedules are enforced through automated deletion or anonymization where technically feasible. (3) **Legal holds**: Verify that litigation hold processes prevent deletion of PII subject to legal proceedings. (4) **Disposal methods**: Confirm that disposal methods are appropriate for the media type: (a) Digital — secure deletion using overwriting (NIST SP 800-88), cryptographic erasure, or physical destruction, (b) Paper — cross-cut shredding or pulping, (c) Backup media — verified deletion across all backup copies, (d) Third-party systems — verified deletion certificates from vendors. (5) **Processor obligations**: Under ISO 27701 Clause 8.4, processors must return or delete all PII upon contract termination unless retention is required by law. Verify deletion certificates are obtained from all processors upon contract termination. (6) **Evidence**: Maintain deletion logs and certificates as evidence for audit.",
          check: "Retention schedule documented for all PII categories. Automated retention enforcement implemented where feasible. Legal hold process documented and tested. Disposal procedures defined for each media type. Deletion certificates obtained from processors upon contract termination. At least one simulated disposal exercise completed. Deletion logs maintained and reviewed. Annual retention review scheduled."
        },
        {
          title: "Assess privacy impact of new systems and changes",
          control: "ISO 27701 Clause 7.7 (privacy by design and by default), GDPR Article 25",
          how: "Implement privacy by design and by default per ISO 27701 Clause 7.7 and GDPR Article 25. Verify that: (1) **Change management integration**: Privacy impact is assessed as part of your change management process. No new system, feature, or processing activity goes live without a privacy review. (2) **Design requirements**: Privacy requirements are included in system design specifications — data minimization (collect only what is needed), purpose limitation (enforce at the technical level), default settings (most privacy-protective settings by default), pseudonymization and anonymization where possible. (3) **Technical measures**: Verify that new systems implement: encryption at rest and in transit, access controls with least privilege, logging and monitoring of PII access, data masking in non-production environments, secure APIs for PII exchange. (4) **DPIA trigger**: Confirm that the privacy review for new systems triggers a DPIA when processing meets the high-risk criteria. (5) **Testing**: Privacy test cases are included in QA testing (e.g., verify consent enforcement, verify data deletion, verify access controls, verify cross-border data flow restrictions). (6) **Procurement**: Third-party vendors are assessed for privacy compliance before procurement (ISO 27701 Clause 7.4). Integrate these checks into your SDLC and procurement workflows.",
          check: "Privacy impact assessment integrated into change management process. Privacy requirements template added to system design specifications. Privacy test cases included in QA test suites. DPIA triggered for at least one new high-risk system. Vendor privacy assessment questionnaire implemented. Default privacy settings verified for at least one product. Evidence of privacy review in change records."
        },
        {
          title: "Conduct privacy-focused internal audit",
          control: "ISO 27701 Clause 9.2 (internal audit), ISO 27001 Clause 9.2",
          how: "Conduct an internal audit of the PIMS focusing on privacy-specific controls: (1) **Audit plan**: Create an annual audit plan covering all PIMS processes, controls, and departments. Auditors must be independent of the area being audited. (2) **Audit scope**: Cover ROPA completeness and accuracy, DPIA process compliance, privacy notice accuracy, DSAR handling effectiveness, consent mechanism functionality, retention and disposal compliance, third-party processor oversight, privacy training completion, incident response readiness for data breaches. (3) **Audit methodology**: Use a combination of document review, staff interviews, technical testing (e.g., verify consent withdrawal propagates, verify data deletion), and walk-through of processes. (4) **Audit criteria**: Benchmark against ISO 27701 requirements, GDPR Articles, applicable national laws, and your own PIMS policies. (5) **Reporting**: Document findings as non-conformities (major/minor) or observations. Classify each finding by risk level. (6) **Follow-up**: Assign corrective actions with owners and deadlines. Track closure. Verify effectiveness of corrective actions. Ensure audit results feed into management review per ISO 27701 Clause 9.3.",
          check: "Annual internal audit plan for PIMS completed. Audit executed by independent auditors. Non-conformities classified and assigned to owners. Corrective action plans with deadlines documented. Follow-up audit scheduled for major findings. Audit report reviewed by DPO and management. Audit results fed into management review."
        }
      ]
    },
    {
      week: 4,
      title: "Certification — Audit Prep, Multi-Framework Integration & Multi-Cloud",
      description:
        "Prepare for PIMS certification audits, integrate ISO 27701 with other privacy frameworks (GDPR, CCPA, LGPD, DPDPA), implement multi-cloud privacy controls across AWS, Azure, GCP, and Alibaba, and address common certification findings and remediation strategies.",
      tasks: [
        {
          title: "Prepare for ISO 27701 PIMS certification audit",
          control: "ISO 27701 Clause 9 (performance evaluation), Clause 10 (improvement), ISO 17021 (certification bodies)",
          how: "Prepare for external certification by a recognized certification body (CB) accredited to ISO 17021. (1) **Pre-assessment**: Engage the CB for a pre-assessment or gap analysis 3–6 months before target certification date. This identifies areas needing remediation without formal results. (2) **Documentation readiness**: Ensure all required documentation is complete and version-controlled: PIMS scope statement, privacy policy, risk assessment and treatment plan, ROPA, DPIA register, privacy notices, DSAR procedures, retention schedules, processor agreements, training records, incident response plan, internal audit reports, management review minutes. (3) **Stage 1 audit (documentation review)**: The CB reviews your PIMS documentation to determine readiness for Stage 2. Ensure documentation covers all ISO 27701 clauses and that your organization understands the standard's requirements. (4) **Stage 2 audit (implementation audit)**: The CB interviews staff, reviews evidence of implementation, observes processes, and verifies that the PIMS is operational and effective. Prepare by: conducting mock audits, briefing staff on what auditors will ask, ensuring evidence is accessible, reviewing recent DSARs, consent records, DPIA documents, and audit logs. (5) **Address non-conformities**: If findings arise, create corrective actions with root cause analysis and evidence of correction within the timeframe agreed with the CB. (6) **Surveillance audits**: Plan for annual surveillance audits (typically Years 1 and 2) and recertification audit in Year 3.",
          check: "Pre-assessment completed with CB or internal gap analysis. All PIMS documentation complete and version-controlled. Stage 1 audit passed (documentation review). Mock audit conducted with staff briefing. Evidence packages prepared for all PIMS processes. Stage 2 audit scheduled. Corrective action process for CB findings documented."
        },
        {
          title: "Integrate ISO 27701 with GDPR, CCPA, LGPD, and DPDPA",
          control: "ISO 27701 Clause 5.2 (integration with ISMS), cross-framework mapping",
          how: "Create a unified privacy compliance program that satisfies multiple frameworks simultaneously: (1) **GDPR**: ISO 27701 is designed to operationalize GDPR. Map ISO 27701 Clauses 7 (controllers) and 8 (processors) directly to GDPR Articles. Key mappings: Art. 30 (ROPA) → ISO 27701 ROPA requirements; Art. 25 (privacy by design) → Clause 7.7; Art. 33/34 (breach notification) → Clause 7.9 and Annex A.8.3; Art. 35 (DPIA) → Clause 7.8; Art. 28 (processor) → Clause 8.3. (2) **CCPA/CPRA**: Map ISO 27701 controls to CCPA requirements: right to know (CCPA §1798.100), right to delete (§1798.105), right to opt-out of sale (§1798.120), right to non-discrimination (§1798.125). Use your PIMS privacy notices and consent mechanisms to satisfy CCPA disclosure requirements. Implement the 'Do Not Sell or Share My Personal Information' link. CPRA's risk assessment requirements align with ISO 27701's DPIA provisions. (3) **LGPD (Brazil)**: LGPD Articles 37 (ROPA equivalent), 38 (DPO), 41 (DPIA), and 46 (international transfers) map well to ISO 27701 requirements. LGPD's legal bases (Art. 7) align with GDPR Art. 6 — document both in your ROPA. (4) **DPDPA (India)**: India's Digital Personal Data Protection Act 2023 requires consent-based processing, data fiduciary obligations, and significant data fiduciary assessments. Map DPDPA requirements to ISO 27701: consent mechanisms (Clause 7.3), grievance redressal (Clause 8.5), cross-border transfer rules. (5) **Unified controls**: Create a control matrix showing which ISO 27701 controls satisfy requirements of each framework, reducing duplication.",
          check: "Cross-framework control matrix created mapping ISO 27701 to GDPR, CCPA/CPRA, LGPD, and DPDPA. Unified ROPA satisfies GDPR Art. 30, LGPD Art. 37, and other ROPA-equivalent requirements. Privacy notices updated to cover multiple frameworks. Consent mechanisms satisfy both GDPR and LGPD requirements. CCPA 'Do Not Sell' link implemented alongside GDPR consent. DPIA process addresses GDPR Art. 35, LGPD Art. 41, and CPRA risk assessment requirements."
        },
        {
          title: "Implement multi-cloud privacy controls across AWS, Azure, GCP, and Alibaba",
          control: "ISO 27701 Clause 7.10 (transfer of PII to third countries), Annex A.7.1–7.5 (transfers)",
          how: "Organizations operating across multiple cloud providers must implement consistent privacy controls. Address data residency, encryption, access control, and logging in each cloud: (1) **AWS**: Use AWS Config Rules for compliance monitoring, AWS Macie for PII discovery in S3, AWS KMS for encryption key management, AWS CloudTrail for audit logging, AWS Data Processing Addendum for GDPR compliance, AWS Regions for data residency (choose regions to keep data in required jurisdictions), AWS IAM for least-privilege access. (2) **Azure**: Use Azure Policy for compliance enforcement, Azure Purview for data discovery and classification, Azure Key Vault for encryption, Azure Activity Log for audit, Microsoft DPA for GDPR compliance, Azure Regions/Availability Zones for data residency, Azure RBAC for access control, Azure Confidential Computing for processing-sensitive data. (3) **GCP**: Use Google Cloud DLP API for PII discovery, Cloud Audit Logs for logging, Cloud KMS for encryption, VPC Service Controls for data boundary, Google Cloud DPA for GDPR compliance, GCP Regions/Location Policies for data residency, IAM for access control. (4) **Alibaba Cloud**: Use Data Security Center for PII discovery, KMS for encryption, ActionTrail for audit logging, Alibaba Cloud DPA for GDPR compliance, Regions for data residency (critical for Asia-Pacific data localization requirements like China's PIPL, India's DPDPA, and Singapore's PDPA). (5) **Unified governance**: Implement a centralized privacy governance layer that: monitors PII across all clouds, enforces consistent retention and disposal, provides consolidated DSAR response capability, maintains a unified ROPA spanning all cloud environments, tracks cross-cloud data transfers, ensures consistent encryption standards.",
          check: "Cloud-specific PII discovery tools configured in each environment (Macie, Purview, DLP API, Data Security Center). Encryption at rest and in transit verified in all clouds. Audit logging enabled and centralized. Data residency controls configured — verified PII stored only in approved regions. DPAs in place with all cloud providers. Cross-cloud data flows mapped. Unified DSAR response capability tested. ROPA updated to reflect all cloud environments."
        },
        {
          title: "Address common ISO 27701 certification findings and remediation",
          control: "ISO 27701 Clauses 6.1.2 (risk assessment), 7.x and 8.x (controls), 10.1 (nonconformity)",
          how: "Learn from the most common certification findings to avoid them: (1) **Incomplete ROPA**: Many organizations fail to maintain a comprehensive, up-to-date ROPA. Remediation: Automate ROPA updates, integrate with data discovery tools, assign ROPA owners per business unit, review quarterly. (2) **Inadequate DPIA process**: DPIAs not conducted when required, or conducted superficially. Remediation: Implement DPIA screening checklist in change management, train project managers on triggers, use standardized templates. (3) **Privacy notices not reflecting actual processing**: Notices contain generic statements rather than specific processing descriptions. Remediation: Map each notice to actual processing activities in ROPA, review notices against ROPA quarterly. (4) **Consent mechanisms non-compliant**: Pre-ticked boxes, bundled consent, no withdrawal mechanism. Remediation: Implement proper CMP, test withdrawal flow, document consent records. (5) **DSAR process gaps**: Missing identity verification, no exemption documentation, response time exceeded. Remediation: Create DSAR runbook, train frontline staff, implement tracking system. (6) **Processor management gaps**: Missing or outdated DPAs, no sub-processor oversight. Remediation: Inventory all processors, execute updated DPAs, implement annual processor assessments. (7) **Insufficient awareness training**: Staff unaware of privacy policies and procedures. Remediation: Implement role-based privacy training, track completion, test knowledge. (8) **No measurement of privacy effectiveness**: No metrics or KPIs for the PIMS. Remediation: Track DSAR volumes, consent rates, DPIA completion rates, privacy incidents, training completion.",
          check: "Review of common findings checklist completed. Each finding type assessed against current organization state. Remediation actions planned for any identified gaps. ROPA, DPIA, notices, consent, DSAR, and processor management all reviewed against common findings. Privacy metrics/KPIs defined and tracking implemented. Staff training gap assessment completed."
        },
        {
          title: "Establish continuous PIMS improvement and monitoring",
          control: "ISO 27701 Clause 9.1 (monitoring, measurement, analysis), Clause 9.3 (management review), Clause 10 (improvement)",
          how: "Sustain your PIMS beyond initial certification: (1) **Privacy metrics and KPIs**: Track and report on: DSAR volume and average response time, consent rates and withdrawal rates, DPIA completion rate, privacy incidents/breaches, training completion rate, ROPA accuracy rate (verified during audits), processor assessment completion rate, retention schedule compliance rate, privacy notice review completion. (2) **Management review**: Conduct at least annual management reviews covering: PIMS performance, audit findings, DSAR metrics, incident trends, regulatory changes, risk assessment updates, resource needs, improvement opportunities. (3) **Regulatory monitoring**: Subscribe to regulatory updates from relevant DPAs (ICO, CNIL, Garante, etc.). Monitor evolving requirements from: GDPR amendments, CCPA/CPRA regulations, LGPD guidance, DPDPA implementing rules, new jurisdiction privacy laws. (4) **Continuous improvement**: Implement a privacy incident and near-miss reporting system. Conduct post-incident reviews and update controls. Benchmark against industry peers. Participate in privacy communities (IAPP, ISACA). (5) **Technology updates**: Monitor new privacy-enhancing technologies (PETs) — differential privacy, homomorphic encryption, federated learning, synthetic data generation. Evaluate applicability to your processing. (6) **Annual PIMS health check**: Comprehensive review of all PIMS components annually, including a gap analysis against any new versions or amendments to ISO 27701.",
          check: "Privacy metrics dashboard created and reporting to management quarterly. Annual management review conducted with documented minutes. Regulatory monitoring process established. Privacy incident reporting system operational. Post-incident reviews completed for any incidents. Annual PIMS health check scheduled. Continuous improvement log maintained. Technology assessment for PETs completed."
        }
      ]
    }
  ]
};

export default function Iso27701Page() {
  return <LearningFrameworkPage framework={FRAMEWORK} />;
}

export { FRAMEWORK };
